// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyxWZdMODmN2hU1-4aFBZmSd6jZEsEWyM',
    appId: '1:671779815647:web:7268f920b00319922c696a',
    messagingSenderId: '671779815647',
    projectId: 'test2-bcbfe',
    authDomain: 'test2-bcbfe.firebaseapp.com',
    storageBucket: 'test2-bcbfe.appspot.com',
    measurementId: 'G-7R04SN2G79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvg0hpuh5qlgeixbnD_ml5p4WbMcc417M',
    appId: '1:671779815647:android:699369f6587e7e7b2c696a',
    messagingSenderId: '671779815647',
    projectId: 'test2-bcbfe',
    storageBucket: 'test2-bcbfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0O81-J4tbLkCOs_oOvTjEcm-8Gb6Kg7A',
    appId: '1:671779815647:ios:8b53f21c18ee5a172c696a',
    messagingSenderId: '671779815647',
    projectId: 'test2-bcbfe',
    storageBucket: 'test2-bcbfe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0O81-J4tbLkCOs_oOvTjEcm-8Gb6Kg7A',
    appId: '1:671779815647:ios:8b53f21c18ee5a172c696a',
    messagingSenderId: '671779815647',
    projectId: 'test2-bcbfe',
    storageBucket: 'test2-bcbfe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyxWZdMODmN2hU1-4aFBZmSd6jZEsEWyM',
    appId: '1:671779815647:web:49febfe1298dcba12c696a',
    messagingSenderId: '671779815647',
    projectId: 'test2-bcbfe',
    authDomain: 'test2-bcbfe.firebaseapp.com',
    storageBucket: 'test2-bcbfe.appspot.com',
    measurementId: 'G-FN54JXHSEH',
  );
}
